use_frameworks!
source 'https://github.com/cocoapods/specs.git'
plugin 'cocoapods-imy-bin'

platform :ios, '12.0'

target 'ICEBase_Example' do
  pod 'ICEBase', :path => '../'

  pod 'AFNetworking'
#  pod 'YYModel',:podspec => 'https://github.com/ibireme/YYModel/raw/master/YYModel.podspec'

end

