#use_frameworks!

platform :ios, '12.0'

target 'ICEBase_Example' do
  pod 'ICEBase', :path => '../'

  pod 'AFNetworking'
#  pod 'YYModel',:podspec => 'https://github.com/ibireme/YYModel/raw/master/YYModel.podspec'

end

